# \uB85C\uADF8 \uCD9C\uB825 \uC124\uC815
module.log=com.p6spy.engine.spy.appender.Slf4JLogger
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
appender.slf4j.category=jdbc.sqlonly
appender.slf4j.logMessageFormat=true

# SQL \uBCF4\uAE30 \uD3B8\uD558\uAC8C
customLogMessageFormat=%(currentTime)|%(executionTime)|%(category)|connection%(connectionId)|%(sqlSingleLine)
